Add a product set
---
tags:
  - Product in product set management
  
parameters:
  - name: product_id
    in: query
    description: product_id
    type: string
    required: true
  - name: product_set_id
    in: query
    description: product_set_id
    type: string
    required: true
responses:
  201:
    description: Product set successfuly registered
  400:
    description: Bad request
  401:
    description: Unauthorized
  500:
    description: Error during creating of Product
