delete a product set
---
tags:
      - Product in product set management
parameters:
  - name: product_id
    in: query
    description: product_id
    type: string
    required: true
  - name: product_set_id
    in: query
    description: product_id
    type: string
    required: true
responses:
  200:
    description: Data successfully removed
  400:
    description: Bad Request
  401:
    description: Unauthorized
  404:
    description: Not found
  500:
    description: Internal Server Error