list a product set
---
tags:
      - Product in product set management
parameters:
  - name: product_set_id
    in: query
    description: product_set_id
    type: string
    required: true
responses:
  200:
    description: A list of data
  400:
    description: Error of data
  500:
    description: Internal Server Error